### ISSUE TITLE
Automate Forex Score Calculation

### ISSUE THREAD

**Issue by 9907daniel** [9907daniel/Givplus#6]
Score.csv file is used to provide the values to the clients and is planned to update daily. 

As it plays a crucial role to the platform, instead of manual uploading, Forex files should be automated to create a new csv.file -> send it into backend/files folder by replacing yesterdays. 

This could be done in three ways : 
1) Creating scheduler on local machine 
2) Cloud servers (GCP. AWS EC2..) 
2) Containerized solution in Docker (cron).

Preferred method is GCP as we are planning to deploy the server on GCP.

Priority : Low, Effort : Medium

**Comment by sj-cha** [comment]
Well done
